### ISSUE TITLE
Angular torque marker is dettached with negative z-axis torque

### ISSUE THREAD

**Issue by longjie** [tork-a/dynpick_driver#16] opened 2015-04-17 07:53 UTC
Hi, my dynpick sensor working well.  Thank you very much.

BTW, did you notice rviz visalization is a bit weired when it has negative z-axis torque?
Its circle marker is not on its arrow as I attached ss.

![screenshot from 2015-04-17 16 23 18](https://cloud.githubusercontent.com/assets/238460/7197945/2d5cb262-e522-11e4-979d-6b2c64d28ef5.png)

Do you know anything about this?

**Comment by 130s** [comment] 2015-04-20 07:19
Could you share the captured topic data (maybe by rosbag so that we can more easily playback) of when this happens?

The driver simply publishes [geometry_msgs/WrenchStamped](http://docs.ros.org/api/geometry_msgs/html/msg/WrenchStamped.html) so I suspect RViz isn't handling it right.

**Comment by 130s** [comment] 2015-04-20 10:44
Confirmed on `Indigo` with the simplest case that this issue occurs (not using dynpick_driver package). I'll report on upstream.
![rviz_wrench_torque_dettached](https://cloud.githubusercontent.com/assets/1840401/7228579/82ad9108-e795-11e4-987b-47b8071a188a.png)

**Comment by longjie** [comment] 2015-04-20 13:24
Thank you @130s !

**Comment by k-okada** [comment] 2015-04-21 22:28
the auter of wrench marker was not smart .. 
https://github.com/ros-visualization/rviz/pull/634

--
◉ Kei Okada

**Comment by 130s** [comment] 2015-08-05 21:46
This should be fixed since https://github.com/ros-visualization/rviz/issues/879 is closed.

**Closed by 130s** 2015-08-05 21:46 UTC
